on:
  pull_request:


env:
  # Adding in token so we can use gh CLI
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  issue-parsing:
    runs-on: ubuntu-latest
    steps:
      - name: parse from github event
        run: |
          echo ${TITLE} \
          && echo ${BODY} \
          && echo ${NUMBER} \
        env:
          TITLE: ${{ github.event.pull_request.title }}
          BODY: ${{ github.event.pull_request.body }}
          NUMBER: ${{ github.event.pull_request.number }}
      - name: join assignees
        run: |
          # Using name for full name, can also use login for github login
          gh pr view ${{ github.event.pull_request.html_url }} \
                      --json "assignees" --jq '.assignees | map(.name) | join(", ")'
      - name: join labels
        run: |
          gh pr view ${{ github.event.pull_request.html_url }} \
                      --json "labels" --jq '.labels | map(.name) | join(", ")'
      - name: label check
        if: ${{ contains(github.event.pull_request.labels.*.name, 'enhancement') }}
        run : |
          echo "enhancement label found"
      - name: linked issues
        run : |
          gh api graphql \
          -F owner='${{ github.repository_owner }}' \
          -F repo=''${{ github.event.repository.name }}'' \
          -F pr=${{ github.event.pull_request.number }} \
          -f query='
          query ($owner: String!, $repo: String!, $pr: Int!) {
                  repository(owner: $owner, name: $repo) {
                          pullRequest(number: $pr) {
                                  closingIssuesReferences(first: 100) {
                                          nodes {
                                                  number
                                          }
                                  }
                          }
                  }
          }'  --jq '.data.repository.pullRequest.closingIssuesReferences.nodes[].number'
